AWSTemplateFormatVersion: "2010-09-09"
Description: Handles auto-cancellations for membership and subscriptions, using API Gateway and Lambda

Parameters:
    App:
        Description: Application name
        Type: String
        Default: zuora-auto-cancel
    Stage:
        Description: Stage name
        Type: String
        AllowedValues:
            - PROD
            - CODE
        Default: CODE

Resources:
    ZuoraAutoCancelRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub ZuoraAutoCancel-${Stage}
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                             - lambda.amazonaws.com
                      Action:
                          - sts:AssumeRole
            Path: /
            Policies:
                - PolicyName: LambdaPolicy
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action:
                            - logs:CreateLogGroup
                            - logs:CreateLogStream
                            - logs:PutLogEvents
                            - lambda:InvokeFunction
                            Resource: "*"
                - PolicyName: SQSPutInQueue
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action: sqs:*
                            Resource: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:subs-welcome-email
                - PolicyName: ReadPrivateCredentials
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action: s3:GetObject
                            Resource: !Sub arn:aws:s3:::payment-failure-lambdas-private/${Stage}/*

    ZuoraAutoCancelLambda:
        Type: AWS::Lambda::Function
        Properties:
            Description: Handles auto-cancellations for membership and subscriptions
            FunctionName:
                !Sub zuora-auto-cancel-${Stage}
            Code:
                S3Bucket: zuora-auto-cancel-dist
                S3Key: !Sub membership/${Stage}/zuora-auto-cancel/zuora-auto-cancel.jar
            Handler: com.gu.autoCancel.AutoCancelHandler::handleRequest
            Environment:
                Variables:
                  Stage: !Ref Stage
            Role:
                Fn::GetAtt:
                - ZuoraAutoCancelRole
                - Arn
            MemorySize: 512
            Runtime: java8
            Timeout: 300
        DependsOn:
        - ZuoraAutoCancelRole

    PaymentFailureLambda:
        Type: AWS::Lambda::Function
        Properties:
            Description: handles zuora payment failure callouts
            FunctionName:
                !Sub payment-failure-${Stage}
            Code:
                S3Bucket: zuora-auto-cancel-dist
                S3Key: !Sub membership/${Stage}/zuora-auto-cancel/zuora-auto-cancel.jar
            Environment:
                Variables:
                  Stage: !Ref Stage
            Handler: com.gu.paymentFailure.Lambda::handleRequest
            Role:
                Fn::GetAtt:
                - ZuoraAutoCancelRole
                - Arn
            MemorySize: 512
            Runtime: java8
            Timeout: 300
        DependsOn:
        - ZuoraAutoCancelRole

    ZuoraAutoCancelAPIPermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:invokeFunction
            FunctionName: !Sub zuora-auto-cancel-${Stage}
            Principal: apigateway.amazonaws.com
        DependsOn: ZuoraAutoCancelLambda
    PaymentFailureAPIPermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:invokeFunction
            FunctionName: !Sub payment-failure-${Stage}
            Principal: apigateway.amazonaws.com
        DependsOn: PaymentFailureLambda

    ZuoraAutoCancelAPI:
        Type: "AWS::ApiGateway::RestApi"
        Properties:
            Description: Zuora sends a callout to this endpoint to initiate an auto-cancellation on an overdue subscription
            Name: !Sub zuora-auto-cancel-api-${Stage}

    ZuoraAutoCancelProxyResource:
        Type: AWS::ApiGateway::Resource
        Properties:
            RestApiId: !Ref ZuoraAutoCancelAPI
            ParentId: !GetAtt [ZuoraAutoCancelAPI, RootResourceId]
            PathPart: auto-cancel
        DependsOn: ZuoraAutoCancelAPI

    PaymentFailureProxyResource:
        Type: AWS::ApiGateway::Resource
        Properties:
            RestApiId: !Ref ZuoraAutoCancelAPI
            ParentId: !GetAtt [ZuoraAutoCancelAPI, RootResourceId]
            PathPart: payment-failure
        DependsOn: ZuoraAutoCancelAPI

    ZuoraAutoCancelMethod:
        Type: AWS::ApiGateway::Method
        Properties:
            AuthorizationType: NONE
            RestApiId: !Ref ZuoraAutoCancelAPI
            ResourceId: !Ref ZuoraAutoCancelProxyResource
            HttpMethod: POST
            RequestParameters:
              method.request.querystring.apiClientId: true
              method.request.querystring.apiToken: true
            Integration:
              Type: AWS_PROXY
              IntegrationHttpMethod: POST
              Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ZuoraAutoCancelLambda.Arn}/invocations
        DependsOn:
        - ZuoraAutoCancelAPI
        - ZuoraAutoCancelLambda
        - ZuoraAutoCancelProxyResource

    PaymentFailureMethod:
        Type: AWS::ApiGateway::Method
        Properties:
            AuthorizationType: NONE
            RestApiId: !Ref ZuoraAutoCancelAPI
            ResourceId: !Ref PaymentFailureProxyResource
            HttpMethod: POST
            RequestParameters:
              method.request.querystring.apiClientId: true
              method.request.querystring.apiToken: true
            Integration:
              Type: AWS_PROXY
              IntegrationHttpMethod: POST
              Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PaymentFailureLambda.Arn}/invocations
        DependsOn:
        - ZuoraAutoCancelAPI
        - ZuoraAutoCancelLambda
        - ZuoraAutoCancelProxyResource

    ZuoraAutoCancelAPIStage:
        Type: AWS::ApiGateway::Stage
        Properties:
            Description: Stage for zuora-auto-cancel-api
            RestApiId: !Ref ZuoraAutoCancelAPI
            DeploymentId: !Ref ZuoraAutoCancelAPIDeployment
            StageName: !Sub ${Stage}
        DependsOn: ZuoraAutoCancelMethod

    ZuoraAutoCancelAPIDeployment:
        Type: AWS::ApiGateway::Deployment
        Properties:
            Description: Deploys zuora-auto-cancel-api into an environment/stage
            RestApiId: !Ref ZuoraAutoCancelAPI
        DependsOn: ZuoraAutoCancelMethod



