AWSTemplateFormatVersion: "2010-09-09"
Description: Handles auto-cancellations for membership and subscriptions, using API Gateway and Lambda

Parameters:
    App:
        Description: Application name
        Type: String
        Default: zuora-auto-cancel
    Stage:
        Description: Stage name
        Type: String
        AllowedValues:
            - PROD
            - UAT
        Default: UAT

Resources:
    ZuoraAutoCancelRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                             - lambda.amazonaws.com
                      Action:
                          - sts:AssumeRole
            Path: /
            Policies:
                - PolicyName: LambdaPolicy
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action:
                            - logs:CreateLogGroup
                            - logs:CreateLogStream
                            - logs:PutLogEvents
                            - lambda:InvokeFunction
                            Resource: "*"

    ZuoraAutoCancelKMS:
        Type: AWS::KMS::Key
        Properties:
            Description: !Sub Used by the ${App} lambda to encrypt and decrypt environment variables
            KeyPolicy:
              Version: '2012-10-17'
              Id: key-policy-zuora-auto-cancel
              Statement:
              - Sid: Enable IAM User Permissions
                Effect: Allow
                Principal:
                  AWS:
                    !Sub arn:aws:iam::${AWS::AccountId}:root
                Action: kms:*
                Resource: "*"
              - Sid: Allow access for Key Administrators
                Effect: Allow
                Action:
                - kms:Create*
                - kms:Describe*
                - kms:Enable*
                - kms:List*
                - kms:Put*
                - kms:Update*
                - kms:Revoke*
                - kms:Disable*
                - kms:Get*
                - kms:Delete*
                - kms:ScheduleKeyDeletion
                - kms:CancelKeyDeletion
                Resource: "*"
              - Sid: Allow use of the key
                Effect: Allow
                Principal:
                  AWS:
                    Fn::GetAtt:
                    - ZuoraAutoCancelRole
                    - Arn
                Action:
                - kms:Encrypt
                - kms:Decrypt
                - kms:ReEncrypt*
                - kms:GenerateDataKey*
                - kms:DescribeKey
                Resource: "*"
        DependsOn: ZuoraAutoCancelRole


    ZuoraAutoCancelLambda:
        Type: AWS::Lambda::Function
        Properties:
            Description: Handles auto-cancellations for membership and subscriptions
            FunctionName:
                !Sub ${App}-${Stage}
            Environment:
                Variables:
                  ZuoraRestUrl: ""
                  ZuoraUsername: ""
                  ZuoraPassword: ""
            Code:
                S3Bucket: zuora-auto-cancel-dist
                S3Key: !Sub ${Stage}/${App}.zip
            Handler: com.gu.zuora-auto-cancel.Lambda::handleRequest
            Role:
                Fn::GetAtt:
                - ZuoraAutoCancelRole
                - Arn
            KmsKeyArn:
                Fn::GetAtt:
                - ZuoraAutoCancelKMS
                - Arn
            MemorySize: 512
            Runtime: java8
            Timeout: 300
        DependsOn:
        - ZuoraAutoCancelRole
        - ZuoraAutoCancelKMS

    ZuoraAutoCancelAPIPermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:invokeFunction
            FunctionName: !Sub ${App}-${Stage}
            Principal: apigateway.amazonaws.com
        DependsOn: ZuoraAutoCancelLambda

    ZuoraAutoCancelAPI:
        Type: "AWS::ApiGateway::RestApi"
        Properties:
            Description: Rest Api to trigger zuora-auto-cancel-api
            Name: zuora-auto-cancel-api

    ZuoraAutoCancelProxyResource:
        Type: AWS::ApiGateway::Resource
        Properties:
            RestApiId: !Ref ZuoraAutoCancelAPI
            ParentId: !GetAtt [ZuoraAutoCancelAPI, RootResourceId]
            PathPart: '{proxy+}'
        DependsOn: ZuoraAutoCancelAPI

    ZuoraAutoCancelMethod:
        Type: AWS::ApiGateway::Method
        Properties:
            AuthorizationType: NONE
            RestApiId: !Ref ZuoraAutoCancelAPI
            ResourceId: !Ref ZuoraAutoCancelProxyResource
            HttpMethod: ANY
            AuthorizationType: NONE
            Integration:
              Type: AWS_PROXY
              IntegrationHttpMethod: POST
              Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ZuoraAutoCancelLambda.Arn}/invocations
        DependsOn:
        - ZuoraAutoCancelAPI
        - ZuoraAutoCancelLambda
        - ZuoraAutoCancelProxyResource

    ZuoraAutoCancelAPIStage:
        Type: AWS::ApiGateway::Stage
        Properties:
            Description: Stage for zuora-auto-cancel-api
            RestApiId: !Ref ZuoraAutoCancelAPI
            DeploymentId: !Ref ZuoraAutoCancelAPIDeployment
            StageName: !Sub ${Stage}
        DependsOn: ZuoraAutoCancelMethod

    ZuoraAutoCancelAPIDeployment:
        Type: AWS::ApiGateway::Deployment
        Properties:
            Description: Deploys zuora-auto-cancel-api into an environment/stage
            RestApiId: !Ref ZuoraAutoCancelAPI
        DependsOn: ZuoraAutoCancelMethod



