AWSTemplateFormatVersion: "2010-09-09"
Description: AWS Lambda - Handles auto-cancellations for membership and subscriptions
Parameters:
    Stack:
        Description: Stack name
        Type: String
        Default: MemSub::Membership Admin::Auto-Cancel Handler-zuora-auto-cancel
    App:
        Description: Application name
        Type: String
        Default: zuora-auto-cancel
    Stage:
        Description: Stage name
        Type: String
        AllowedValues:
            - PROD
            - CODE
        Default: CODE

Resources:
    zuora-auto-cancelRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                             - lambda.amazonaws.com
                      Action:
                          - sts:AssumeRole
            Path: /
            Policies:
                - PolicyName: LambdaPolicy
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action:
                                - logs:CreateLogGroup
                                - logs:CreateLogStream
                                - logs:PutLogEvents
                                - lambda:InvokeFunction
                            Resource: "*"

    Lambda:
        Type: AWS::Lambda::Function
        Properties:
            FunctionName:
                !Sub zuora-auto-cancel-${Stage}
            Environment:
                Variables:
                # Add your config/environment variables here.

            Code:
                S3Bucket: MemSub::Membership Admin::Auto-Cancel Handler-dist
                S3Key:
                    !Sub ${Stack}/${Stage}/zuora-auto-cancel/zuora-auto-cancel.zip
            Description: Handles auto-cancellations for membership and subscriptions
            Handler: com.gu.zuora-auto-cancel.Lambda::handleRequest
            MemorySize: 256
            Role:
                Fn::GetAtt:
                - zuora-auto-cancelRole
                - Arn
            Runtime: java8
            Timeout: 300

    #
    # Add your Lambda trigger rule and permissions here.
    #
    #
    #
